version: "3"
services:
  qgis:
    build:
      context: .
    volumes:
      - ./..:/storage
    tty: true
    # run a python file that calls all of the tests
    command: sh storage/.docker/run_test.sh
